### ISSUE TITLE
Validator Offline Problems

### ISSUE THREAD

**Issue by nodexone** [chainflip-io/support#1]
Description: 
- My logs are fine but nodes are still offline, i run a nodes not in superuser, but custom user like on docs tutorials and also some LVM configurations https://cdn.discordapp.com/attachments/1033451519347007489/1094726705727406090/image.png, so chainflip node database strored on `/data/chainflip/chainflip/chaindata` keys on `/data/chainflip/chainflip/keys` but chainflip repo still on `/etc/apt/keyrings`/ and also i use rpc provider from others like https://dashboard.blockpi.io/, logs are all running normally exactly as in docs and i have followed everything but until now still **offline**, of course I've already staked more than the minimum auction limit, and there's another problem I can't see my node list in the `My Nodes` dashboard.

Proof:
- chainflip-engine : https://cdn.discordapp.com/attachments/1025129818964099212/1094694596103118890/image.png
- chainflip-node : https://cdn.discordapp.com/attachments/1025129818964099212/1094694713392648262/image.png
- validator status : https://cdn.discordapp.com/attachments/1025129818964099212/1094695310024003646/image.png
- Dashboard : https://cdn.discordapp.com/attachments/1033451519347007489/1094726216176636017/image.png

Validator ID:
- NodeX Master 1 
>- https://blocks-perseverance.chainflip.io/validator/cFMDktAX5BYHgHf36xshfYGxJnWiy7fwrBWLoDf9HfNiuDiiX

- NodeX Master 2
>- https://blocks-perseverance.chainflip.io/validator/cFK18iYSZWC6HHBnbEYRSDRgDPCibvXoAY6jdnjNKGqpMMygN

Environment:
- Operating System: Ubuntu 22.04
- Provider : Hetzner AX41-NVMe 
- AMD Ryzen™ 5 3600
- 6 cores / 12 threads @ 3.6 GHz
- 64 GB DDR4 RAM
- 2 x 512 GB NVMe SSD
- Engine Version: chainflip-engine 0.7.3, chainflip-node 0.7.2

Labels: bug

**Comment by Haafingar** [comment]
The reason that you are offline is that your node is not submitting enough heartbeats. Without detailed logs, we can not help figure out why.

Please connect your nodes to grafana as per the docs instructions or ask for help on discord. Closing for now.
