### ISSUE TITLE
Staked node not displayed on the dashboard

### ISSUE THREAD

**Issue by 0xSleipnir** [chainflip-io/support#2]
After staking on the UI, the transaction is recognized successfully on the blockchain but the node is not shown as staked/registered on the UI.
First notice of the issue: Friday, 7th of April
Last notice: Monday 10th of April

Description:
While staking a new node on the dashboard where there's already an existing one, the new node doesn't appear although the stake/approve transaction goes through. The new node is fully synced and there are obviously no issues in the node's logs, engine and node both working fine.
Same behavior is observed while adding a node from a new account not associated with any nodes previously: stake transaction goes through, the node doesn't appear on the dashboard.
Also, while approving the tokens' amount on the existing node's dashboard before the staking process gets initialized, there have been a couple of times issues with the transaction getting reverted with "out of gas" failure, although the gas limit was initially manually set to the highest level (could be explained because of the recent update of MetaMask where it's necessary to manually approve the spending cap (?)).
Both nodes are reachable through blocks-perseverance.chainflip.io/validator/Node_ID. Staked amount, status and reputation are not displayed.

<img width="1644" alt="Bildschirmfoto 2023-04-11 um 00 25 43" src="https://user-images.githubusercontent.com/106818457/231010661-db1d4065-a224-4488-b8f4-9e715fcf0fd6.png">

<img width="1532" alt="Screenshot 2023-04-11 at 00 27 01" src="https://user-images.githubusercontent.com/106818457/231010967-1969e489-0d41-4342-a45e-4091092b81a3.png">

Logs look as usual.

<img width="1005" alt="Bildschirmfoto 2023-04-11 um 00 38 34" src="https://user-images.githubusercontent.com/106818457/231012278-233eff73-9df0-4584-86ee-f2c375baf9bc.png">

**Environment:**
Operating System: Ubuntu 20.04
System Specification: Hetzner 6 core dedicated i7, 64GB RAM, 1Gbps up/down, Germany, 900GB NVMe disk, raid0
Version: chainflip-engine 0.7.3, chainflip-node 0.7.2

**Comment by Haafingar** [comment]
Tagging @fernandezdavid and @acdibble to update on the issue

**Comment by acdibble** [comment]
There was an issue with our subgraph (https://thegraph.com/hosted-service/subgraph/chainflip-io/perseverance) where indexing of staking events irrecoverably entered an error state. This is a known issue (https://github.com/graphprotocol/graph-node/issues/4190).

Redeploying our subraph successfully resolved the issue.
