### ISSUE TITLE
Slash

### ISSUE THREAD

**Issue by z1onobdy** [chainflip-io/support#5]
Description:
Node got slashed today. I've checked my monitoring for hardware\network issues but all seems ok as usual. No overload or something else.
A link to logs: https://grafana.chainflip.xyz/goto/zBRq5CL4k?orgId=1

Environment:

Operating System: Ubuntu 22.04
System Specification: My own dedicated server, Intel Core i7 13700k, 32GB DDR5 RAM, 300Mbps up/down, Russia, 1Tb NVMe disk
Version: chainflip-engine 0.7.3, chainflip-node 0.7.2, runtime version XYZ

Labels: bug

**Comment by Haafingar** [comment]
There is not a lot we can do with this information, sorry.
